<?php
/**
 * Created by PhpStorm.
 * User: stefan
 * Date: 7.12.17.
 * Time: 09.29
 */
function properties_page_theme(){
    return [
        'properties_page' => array(
            'template' => 'properties_page',
            'variables' => [
                'content' => [],
            ],
        ),
        'from_prop' => array(
            'template' => 'from_prop',
            'variables' => [
                'content' => [],
            ],
        ),

    ];
}